"""Page route: report."""
import re
from fastapi import APIRouter, Request, HTTPException
from fastapi.responses import HTMLResponse
from app.components import wrap_v4_layout
from app.i18n import get_lang
from app.settings import V2_HTML

router = APIRouter(tags=["pages"])


@router.get("/report")
def report(request: Request):
    if not V2_HTML.exists():
        raise HTTPException(status_code=404, detail="v2 report has not been generated yet")
    raw = V2_HTML.read_text(encoding="utf-8")
    # Extract body content
    import re
    body_match = re.search(r'<body>(.*?)</body>', raw, re.DOTALL)
    if not body_match:
        raise HTTPException(status_code=500, detail="Invalid report format")
    body = body_match.group(1)
    # Extract inline CSS (keep v2-specific table/card styles)
    style_match = re.search(r'<style>(.*?)</style>', raw, re.DOTALL)
    v2_css = style_match.group(1) if style_match else ""
    # Remove the :root variables (v4 provides theme)
    v2_css = re.sub(r':root\s*\{[^}]*\}', '', v2_css)
    # Remove body/header/wrap styles (v4 handles these)
    v2_css = re.sub(r'body\s*\{[^}]*\}', '', v2_css)
    v2_css = re.sub(r'header\s*\{[^}]*\}', '', v2_css)
    v2_css = re.sub(r'\.wrap\s*\{[^}]*\}', '', v2_css)
    # Remove old nav links
    v2_css = re.sub(r'\.query-line\s*\{[^}]*\}', '', v2_css)
    # Remove the old <header> block entirely
    body = re.sub(r'<header>.*?</header>', '', body, flags=re.DOTALL)
    # Remove any top nav link rows
    body = re.sub(r'<div class="query-line">.*?</div>\s*</header>', '', body, flags=re.DOTALL)
    # Remove links to old pages ("后端控制台", "API 文档", etc.)
    body = re.sub(r'<a href="/"[^>]*>.*?</a>', '', body)
    body = re.sub(r'<a href="[^"]*">后端控制台</a>', '', body)
    body = re.sub(r'<a href="[^"]*">API 文档</a>', '', body)
    body = re.sub(r'<a href="[^"]*">Exposure API</a>', '', body)
    body = re.sub(r'<a href="[^"]*">图表 API</a>', '', body)
    # The audit report is intentionally limited to cost + reconciliation (overview /
    # api-reconcile / holdings / notes). The ETF look-through and holdings-analysis
    # ("radar": price / options / market value / P&L) sections — which duplicated
    # Portfolio Lab — are no longer generated by build_portfolio_html.py, so no
    # post-processing removal is needed here anymore.
    # Add btn class to buttons inside report
    body = body.replace('id="exportCsv" type="button"', 'id="exportCsv" class="btn" type="button"')
    body = body.replace('id="exportT212Csv" type="button"', 'id="exportT212Csv" class="btn" type="button"')
    body = body.replace('id="toggleT212Reconcile" class="ghost-button" type="button"', 'id="toggleT212Reconcile" class="btn" type="button"')
    # Keep the rest of the v2 styles for tables, cards, badges etc.
    content = f"""<div class="audit-note">这是审计报表：保留完整成本、账户对账、收入统计和导出。组合决策、风险、估值和模型分析请使用 Portfolio Lab。</div>
{body}
"""
    return HTMLResponse(wrap_v4_layout("审计报表", content, "/report", get_lang(request), head_extra='<link rel="stylesheet" href="/static/report.css" />'))


@router.post("/api/log-error")
def log_error_endpoint(data: dict):
    print("=== BROWSER JS ERROR ===")
    print(data.get("message"))
    print(data.get("stack"))
    print("========================")
    return {"status": "ok"}

